apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgat-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kgat-backend
  template:
    metadata:
      labels:
        app: kgat-backend
    spec:
      containers:
        - name: kgat-backend
          image: kgat-backend-image:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kgat-backend-svc
spec:
  selector:
    app: kgat-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None
