# kgat-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgat-frontend
  namespace: kgat
  labels:
    app: kgat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kgat-frontend
  template:
    metadata:
      labels:
        app: kgat-frontend
    spec:
      imagePullSecrets:
      - name: ecr-secret  # 이 부분 추가
      containers:
      - name: kgat-frontend
        image: 676206900599.dkr.ecr.ap-northeast-2.amazonaws.com/kgat-frontend:95c098b1d3d216acb4372a2f9c9786b2434b996e
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kgat-frontend-svc
  namespace: kgat
spec:
  selector:
    app: kgat-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
