apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgat-backend
  namespace: kgat-backend
  labels:
    app: kgat-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kgat-backend
  template:
    metadata:
      labels:
        app: kgat-backend
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
        - name: kgat-backend
          image: 676206900599.dkr.ecr.ap-northeast-2.amazonaws.com/kgat-backend:f0cd6c8c5d6ca63d8f1d95831361c732582c032a
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kgat-backend-svc
  namespace: kgat-backend
spec:
  selector:
    app: kgat-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
